name: 'Github Action Control'
description: 'Enforce Github Action policy'
author: 'ihavespoons'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for API access'
    default: ${{ github.token }}
    required: false
  github_repository:
    description: 'GitHub repository to enforce policy on'
    required: false
    default: ${{ github.repository }}
  output_format:
    description: 'Output format for report (markdown or json)'
    required: false
    default: 'markdown'
  policy_content:
    description: 'Policy configuration content as a string (will be used exclusively, ignoring local policy files)'
    required: true

runs:
  using: 'docker'
  image: docker://ihavespoons/action-control:latest
  args:
    - enforce
    - '--repo'
    - ${{ inputs.github_repository }}
    - '--output'
    - ${{ inputs.output_format }}
    - '--github-token'
    - ${{ inputs.github_token }}
    - '--policy-content'
    - ${{ inputs.policy_content }}
