name: 'Action Control'
description: 'Enforce Github Action policy'
author: 'Ben Gittins'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
  organization:
    description: 'GitHub organization to analyze'
    required: false
  repository:
    description: 'Specific repository to analyze (format: owner/repo)'
    required: false
  output_format:
    description: 'Output format for report (markdown or json)'
    required: false
    default: 'markdown'
  policy_content:
    description: 'Policy configuration content as a string (will be used exclusively, ignoring local policy files)'
    required: true

runs:
  using: 'docker'
  image: ihavespoons/action-control:latest
  args:
    - enforce
    - '--org'
    - ${{ inputs.organization }}
    - '--repo'
    - ${{ inputs.repository }}
    - '--output'
    - ${{ inputs.output_format }}

env:
  ACTION_CONTROL_GITHUB_TOKEN: ${{ inputs.github_token }}
  ACTION_CONTROL_POLICY_CONTENT: ${{ inputs.policy_content }}