name: Enforce GitHub Actions Policy

on:
  pull_request:
      branches: [main]
  workflow_dispatch: 

jobs:
  enforce-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce GitHub Actions Policy
        uses: ihavespoons/action-control@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          policy_content: ${{ vars.ACTION_CONTROL_POLICY_CONTENT}}