name: Test
on: [pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Run unit tests
        run: go test -v ./internal/...
      - name: Building for integration tests
        run: go build -o bin/action-control
      - name: Run integration tests
        run: go test -v ./tests/...